# Generated by Django 5.2.16 on 2026-08-02 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('opportunities', '0002_opportunity_default_reminders_enabled'),
        ('progress', '0001_initial'),
        ('tasks', '0001_initial'),
        ('travel', '0002_travelplan_default_reminders_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('task_due', 'Task Due'), ('goal_due', 'Goal Due'), ('opportunity_deadline', 'Opportunity Deadline'), ('application_follow_up', 'Application Follow Up'), ('application_next_action', 'Application Next Action'), ('learning_target', 'Learning Target'), ('travel_start', 'Travel Start'), ('travel_itinerary', 'Travel Itinerary'), ('travel_checklist', 'Travel Checklist'), ('custom', 'Custom')], max_length=32)),
                ('scheduled_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='telegram', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=160)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dedupe_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='opportunities.application')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='progress.goal')),
                ('learning_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='learning.learningitem')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='opportunities.opportunity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task')),
                ('travel_checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='travel.travelchecklistitem')),
                ('travel_itinerary_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='travel.travelitineraryitem')),
                ('travel_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='travel.travelplan')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_84d5a7_idx'), models.Index(fields=['owner', 'status', 'scheduled_at'], name='notificatio_owner_i_84c557_idx')],
            },
        ),
    ]
