# Generated by Django 5.2.16 on 2026-08-02 11:03

import decimal
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=16)),
                ('category', models.CharField(choices=[('research', 'Research'), ('university', 'University'), ('career', 'Career'), ('programming', 'Programming'), ('learning', 'Learning'), ('jkkniu_research_society', 'Jkkniu Research Society'), ('health', 'Health'), ('travel', 'Travel'), ('personal', 'Personal'), ('financial', 'Financial'), ('other', 'Other')], default='personal', max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
                ('related_tasks', models.ManyToManyField(blank=True, related_name='goals', to='tasks.task')),
            ],
            options={
                'ordering': ['end_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='other', max_length=32)),
                ('activity_type', models.CharField(choices=[('work', 'Work'), ('research', 'Research'), ('study', 'Study'), ('learning', 'Learning'), ('project', 'Project'), ('meeting', 'Meeting'), ('event', 'Event'), ('application', 'Application'), ('travel', 'Travel'), ('exercise', 'Exercise'), ('personal', 'Personal'), ('other', 'Other')], max_length=20)),
                ('minutes_spent', models.PositiveIntegerField(default=0)),
                ('progress_value', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('result', models.TextField(blank=True)),
                ('challenge', models.TextField(blank=True)),
                ('lesson_learned', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tasks.task')),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='progress.goal')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('summary', models.TextField(blank=True)),
                ('completed_work', models.TextField(blank=True)),
                ('important_achievements', models.TextField(blank=True)),
                ('unfinished_work', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('next_priorities', models.TextField(blank=True)),
                ('productivity_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('learning_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('wellbeing_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('planned_items_count', models.PositiveIntegerField(default=0)),
                ('completed_items_count', models.PositiveIntegerField(default=0)),
                ('total_minutes_spent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['owner', 'period_type', 'status', 'end_date'], name='progress_go_owner_i_ad3fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['owner', 'category', 'start_date'], name='progress_go_owner_i_6ec555_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['owner', 'activity_date', 'category'], name='progress_ac_owner_i_bc5f13_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['owner', 'activity_type', 'activity_date'], name='progress_ac_owner_i_ea2b58_idx'),
        ),
        migrations.AddIndex(
            model_name='progressreview',
            index=models.Index(fields=['owner', 'period_type', 'period_start', 'period_end'], name='progress_pr_owner_i_4d2aa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='progressreview',
            constraint=models.UniqueConstraint(fields=('owner', 'period_type', 'period_start', 'period_end'), name='unique_progress_review_period'),
        ),
    ]
