# Generated by Django 5.2.16 on 2026-08-02 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('normalized_url', models.URLField(max_length=2048)),
                ('source_platform', models.CharField(default='website', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('manual_review_required', 'Manual review required'), ('failed', 'Failed'), ('reviewed', 'Reviewed')], default='pending', max_length=32)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_link', to='opportunities.opportunity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status', 'created_at'], name='capture_cap_owner_i_8fadb3_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'normalized_url'), name='unique_captured_url_per_owner')],
            },
        ),
    ]
