# Generated by Django 5.2.10 on 2026-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Application title', max_length=255)),
                ('organization', models.CharField(help_text='Company/Institution name', max_length=255)),
                ('category', models.CharField(choices=[('job', 'Job'), ('scholarship', 'Scholarship'), ('internship', 'Internship'), ('exam', 'Exam'), ('others', 'Others')], default='job', help_text='Type of application', max_length=20)),
                ('deadline', models.DateField(help_text='Application deadline')),
                ('result_date', models.DateField(blank=True, help_text='Expected result date (optional)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', help_text='Current application status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['deadline', '-created_at'],
            },
        ),
    ]
