# Generated by Django 5.2.16 on 2026-08-02 11:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('skill', models.CharField(blank=True, max_length=120)),
                ('learning_type', models.CharField(choices=[('course', 'Course'), ('book', 'Book'), ('article', 'Article'), ('research_paper', 'Research Paper'), ('video', 'Video'), ('documentation', 'Documentation'), ('practice', 'Practice'), ('workshop', 'Workshop'), ('mentorship', 'Mentorship'), ('other', 'Other')], max_length=24)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('resource_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('dropped', 'Dropped')], default='planned', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('target_hours', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_hours', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_before', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('confidence_after', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('minutes_spent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('topics_covered', models.TextField(blank=True)),
                ('new_knowledge', models.TextField(blank=True)),
                ('practice_completed', models.TextField(blank=True)),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.learningitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learningitem',
            index=models.Index(fields=['owner', 'status', 'target_date'], name='learning_le_owner_i_b04aba_idx'),
        ),
        migrations.AddIndex(
            model_name='learningitem',
            index=models.Index(fields=['owner', 'skill'], name='learning_le_owner_i_03f188_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['owner', 'session_date'], name='learning_le_owner_i_4e2280_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['learning_item', 'session_date'], name='learning_le_learnin_c78dce_idx'),
        ),
    ]
