import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

export const chartColors = { primary: '#0ea5e9', secondary: '#8b5cf6', success: '#10b981', warning: '#f59e0b', grid: '#94a3b8' };
const Box = ({ title, summary, children }) => <section className="card p-5 min-w-0"><h2 className="text-xl font-semibold">{title}</h2><p className="text-sm text-gray-500 mb-4">{summary}</p><div className="h-72 min-w-0" role="img" aria-label={`${title}. ${summary}`}>{children}</div></section>;
const common = { margin: { top: 8, right: 12, left: 0, bottom: 8 } };

export function TrendChart({ data }) { return <Box title="Daily progress trend" summary="Daily completion percentage, work minutes, and learning minutes."><ResponsiveContainer width="100%" height="100%"><LineChart data={data} {...common}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis domain={[0, 'auto']} /><Tooltip /><Legend /><Line type="monotone" dataKey="completion_percentage" name="Completion %" stroke={chartColors.success} /><Line type="monotone" dataKey="work_minutes" name="Work minutes" stroke={chartColors.primary} /><Line type="monotone" dataKey="learning_minutes" name="Learning minutes" stroke={chartColors.secondary} /></LineChart></ResponsiveContainer></Box>; }
export function PlannedChart({ data }) { return <Box title="Planned versus completed" summary="Task counts grouped by week for the selected period."><ResponsiveContainer width="100%" height="100%"><BarChart data={data} {...common}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="label" /><YAxis allowDecimals={false} /><Tooltip /><Legend /><Bar dataKey="planned" name="Planned" fill={chartColors.primary} /><Bar dataKey="completed" name="Completed" fill={chartColors.success} /></BarChart></ResponsiveContainer></Box>; }
export function MonthlyChart({ data }) { return <Box title="Twelve-month trend" summary="Monthly completion percentage, work hours, and learning hours."><ResponsiveContainer width="100%" height="100%"><LineChart data={data} {...common}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Legend /><Line dataKey="completion_percentage" name="Completion %" stroke={chartColors.success} /><Line dataKey="work_hours" name="Work hours" stroke={chartColors.primary} /><Line dataKey="learning_hours" name="Learning hours" stroke={chartColors.secondary} /></LineChart></ResponsiveContainer></Box>; }
export function CategoryChart({ data, metric = 'minutes' }) { return <Box title="Work by category" summary={`Categories ranked using ${metric === 'minutes' ? 'time spent' : 'completed items'}.`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" {...common}><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" /><YAxis dataKey="category" type="category" width={100} tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey={metric} fill={chartColors.primary} /></BarChart></ResponsiveContainer></Box>; }
export function LearningChart({ data }) { return <Box title="Learning by topic" summary="Learning hours sorted from highest to lowest."><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" {...common}><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" /><YAxis dataKey="topic" type="category" width={110} /><Tooltip /><Bar dataKey="hours" fill={chartColors.secondary} /></BarChart></ResponsiveContainer></Box>; }

export function ActivityHeatmap({ data }) {
    const colors = { none: 'bg-gray-100 dark:bg-gray-700', low: 'bg-sky-200', medium: 'bg-sky-400', high: 'bg-sky-600', very_high: 'bg-sky-800' };
    return <section className="card p-5"><h2 className="text-xl font-semibold">Activity heatmap</h2><p className="text-sm text-gray-500 mb-4">Balanced daily score from completed tasks, work, learning, and goal progress. Every cell has a text tooltip and intensity label.</p><div className="grid grid-flow-col grid-rows-7 auto-cols-[14px] gap-1 overflow-x-auto pb-3" role="grid" aria-label="Daily activity heatmap">{data.map((day) => <div key={day.date} role="gridcell" tabIndex="0" aria-label={`${day.date}: ${day.intensity} activity, score ${day.activity_score}, ${day.completed_tasks} tasks, ${day.work_minutes} work minutes, ${day.learning_minutes} learning minutes, ${day.goal_progress_count} goal updates`} title={`${day.date}\nScore: ${day.activity_score}\nTasks: ${day.completed_tasks}\nWork: ${day.work_minutes} min\nLearning: ${day.learning_minutes} min\nGoal updates: ${day.goal_progress_count}`} className={`w-3.5 h-3.5 rounded-sm ${colors[day.intensity]}`} />)}</div><div className="flex gap-3 text-xs text-gray-500"><span>None</span><span>Low</span><span>Medium</span><span>High</span><span>Very high</span></div></section>;
}
