# Generated by Django 5.2.16 on 2026-08-02 10:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('area', models.CharField(choices=[('research', 'Research'), ('university', 'University'), ('career', 'Career'), ('jkkniu_research_society', 'JKKNIU Research Society'), ('programming', 'Programming'), ('learning', 'Learning'), ('travel', 'Travel'), ('personal', 'Personal'), ('other', 'Other')], default='personal', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('actual_minutes', models.PositiveIntegerField(default=0)),
                ('next_action', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('progress_before', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_after', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('work_completed', models.TextField(blank=True)),
                ('blocker', models.TextField(blank=True)),
                ('next_step', models.TextField(blank=True)),
                ('minutes_spent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='tasks.task')),
            ],
            options={
                'ordering': ['-log_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('completed_today', models.TextField(blank=True)),
                ('unfinished_work', models.TextField(blank=True)),
                ('main_blocker', models.TextField(blank=True)),
                ('tomorrow_priority', models.TextField(blank=True)),
                ('productivity_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['owner', 'review_date'], name='tasks_daily_owner_i_80bd61_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'review_date'), name='unique_daily_review_per_owner')],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'status', 'due_at'], name='tasks_task_owner_i_8c8a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'area', 'due_at'], name='tasks_task_owner_i_69ec2c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'created_at'], name='tasks_task_owner_i_14250c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskprogresslog',
            index=models.Index(fields=['owner', 'log_date'], name='tasks_taskp_owner_i_af919e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskprogresslog',
            index=models.Index(fields=['task', 'log_date'], name='tasks_taskp_task_id_e42603_idx'),
        ),
    ]
