# Generated by Django 5.2.16 on 2026-08-02 11:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('personal', 'Personal'), ('academic', 'Academic'), ('conference', 'Conference'), ('research', 'Research'), ('work', 'Work'), ('family', 'Family'), ('tourism', 'Tourism'), ('other', 'Other')], max_length=16)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('planning', 'Planning'), ('booked', 'Booked'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='idea', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('transportation', models.TextField(blank=True)),
                ('accommodation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('item_type', models.CharField(choices=[('transport', 'Transport'), ('accommodation', 'Accommodation'), ('meeting', 'Meeting'), ('conference', 'Conference'), ('activity', 'Activity'), ('meal', 'Meal'), ('other', 'Other')], max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_itinerary_items', to=settings.AUTH_USER_MODEL)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='travel.travelplan')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('documents', 'Documents'), ('booking', 'Booking'), ('packing', 'Packing'), ('finance', 'Finance'), ('academic', 'Academic'), ('work', 'Work'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=16)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='travel.travelplan')),
            ],
            options={
                'ordering': ['is_completed', 'due_at'],
            },
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['owner', 'status', 'start_date'], name='travel_trav_owner_i_49ce63_idx'),
        ),
        migrations.AddIndex(
            model_name='travelitineraryitem',
            index=models.Index(fields=['owner', 'start_at'], name='travel_trav_owner_i_b73342_idx'),
        ),
        migrations.AddIndex(
            model_name='travelchecklistitem',
            index=models.Index(fields=['owner', 'is_completed', 'due_at'], name='travel_trav_owner_i_6d46f6_idx'),
        ),
    ]
