# Generated by Django 5.2.16 on 2026-08-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='default_reminders_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
