# Generated by Django 5.2.16 on 2026-08-02 11:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('scholarship', 'Scholarship'), ('fellowship', 'Fellowship'), ('conference', 'Conference'), ('competition', 'Competition'), ('volunteer', 'Volunteer'), ('other', 'Other')], max_length=20)),
                ('source_platform', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('website', 'Website'), ('email', 'Email'), ('telegram', 'Telegram'), ('other', 'Other')], default='website', max_length=16)),
                ('source_url', models.URLField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('not_specified', 'Not Specified')], default='not_specified', max_length=16)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('funding_or_salary', models.CharField(blank=True, max_length=255)),
                ('contact_information', models.TextField(blank=True)),
                ('extraction_confidence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_deadline_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('captured', 'Captured'), ('reviewing', 'Reviewing'), ('saved', 'Saved'), ('ignored', 'Ignored'), ('expired', 'Expired')], default='captured', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('saved', 'Saved'), ('reviewing', 'Reviewing'), ('preparing_documents', 'Preparing Documents'), ('ready_to_apply', 'Ready To Apply'), ('applied', 'Applied'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('waiting_for_result', 'Waiting For Result'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='saved', max_length=24)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('application_id', models.CharField(blank=True, max_length=120)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('next_action', models.TextField(blank=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('expected_result_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('cv_version', models.CharField(blank=True, max_length=120)),
                ('cover_letter_reference', models.CharField(blank=True, max_length=255)),
                ('documents_checklist', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('submission_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_submission', to='progress.activitylog')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['follow_up_at', 'next_action_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner', 'status', 'deadline'], name='opportuniti_owner_i_ab1428_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner', 'opportunity_type', 'organization'], name='opportuniti_owner_i_c115f3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['owner', 'stage', 'follow_up_at'], name='opportuniti_owner_i_b0d132_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['owner', 'next_action_at'], name='opportuniti_owner_i_25fbea_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('owner', 'opportunity'), name='unique_application_per_opportunity_owner'),
        ),
    ]
