import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { progressApi } from '../../api';
import { Button, Card, PageLoader } from '../../components/ui';
import { ActivityHeatmap, CategoryChart, LearningChart, MonthlyChart, PlannedChart, TrendChart } from '../../components/admin/AnalyticsCharts';

const label = (value) => String(value || '').replaceAll('_', ' ');
export default function AnalyticsPage({ section = 'daily' }) {
    const [params, setParams] = useSearchParams(); const [data, setData] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
    const period = params.get('period') || (section === 'yearly' ? 'yearly' : section === 'monthly' ? 'monthly' : '30d');
    const query = useMemo(() => Object.fromEntries([...params.entries()].concat(params.has('period') ? [] : [['period', period]])), [params, period]);
    useEffect(() => { setLoading(true); setError(''); progressApi.analytics(query).then(setData).catch((e) => setError(e.displayMessage || 'Could not load analytics.')).finally(() => setLoading(false)); }, [query]);
    const update = (key, value) => { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); setParams(next); };
    const exportCsv = async (dataset) => { const blob = await progressApi.exportCsv({ ...query, dataset }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `analytics-${dataset}.csv`; anchor.click(); URL.revokeObjectURL(url); };
    if (loading) return <PageLoader />;
    if (error) return <div role="alert" className="p-4 bg-red-50 text-red-700 rounded-xl">{error}</div>;
    if (!data) return <Card hover={false}>No analytics data.</Card>;
    return <div className="space-y-6"><div><h1 className="text-3xl font-bold">{label(section)} analytics</h1><p className="text-gray-500">Asia/Dhaka · {data.start_date} to {data.end_date}</p></div><div className="flex flex-wrap gap-3 items-end"><label>Period<select value={period} onChange={(e) => update('period', e.target.value)} className="block border rounded-lg p-2"><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="custom">Custom</option></select></label><label>Year<input className="block border rounded-lg p-2 w-28" type="number" value={params.get('year') || new Date().getFullYear()} onChange={(e) => update('year', e.target.value)} /></label><label>Month<input className="block border rounded-lg p-2 w-24" type="number" min="1" max="12" value={params.get('month') || new Date().getMonth() + 1} onChange={(e) => update('month', e.target.value)} /></label><Button variant="secondary" onClick={() => exportCsv(section === 'yearly' ? 'yearly_progress' : 'daily_activity')}>Export CSV</Button></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{Object.entries(data.summary).slice(0, 8).map(([key, value]) => <Card hover={false} key={key}><p className="text-sm text-gray-500 capitalize">{label(key)}</p><p className="text-2xl font-bold">{value ?? '—'}</p></Card>)}</div>{section === 'daily' && <><ActivityHeatmap data={data.activity_heatmap} /><TrendChart data={data.daily_trend} /></>}{section === 'monthly' && <><PlannedChart data={data.planned_vs_completed} /><CategoryChart data={data.category_breakdown} /></>}{section === 'yearly' && <><MonthlyChart data={data.monthly_trend} /><ActivityHeatmap data={data.activity_heatmap} /><GoalProgress rows={data.goal_progress} /></>}{section === 'learning' && <><LearningChart data={data.learning_by_topic} /><TrendChart data={data.daily_trend} /><LearningTable rows={data.learning_items} /></>}{section === 'travel' && <><TravelTimeline rows={data.travel_timeline} /><PlannedChart data={data.travel_budget_comparison.map((x) => ({ label: x.label, planned: x.estimated, completed: x.actual }))} /></>}</div>;
}
const GoalProgress = ({ rows }) => <section className="card p-5"><h2 className="text-xl font-semibold mb-3">Yearly goal progress</h2>{rows.length ? rows.map((row) => <div key={row.id} className="mb-4"><div className="flex justify-between"><span>{row.title} · {row.status} · due {row.end_date}</span><span>{row.current_value}/{row.target_value} ({row.percentage}%)</span></div><div className="h-2 bg-gray-200 rounded"><div className="h-full bg-sky-500 rounded" style={{ width: `${row.percentage}%` }} /></div></div>) : <p>No goals in this period.</p>}</section>;
const LearningTable = ({ rows }) => <section className="card p-5 overflow-x-auto"><h2 className="text-xl font-semibold mb-3">Learning completion</h2><table className="w-full text-sm"><thead><tr><th>Item</th><th>Status</th><th>Hours</th><th>Completion</th><th>Confidence</th></tr></thead><tbody>{rows.map((x) => <tr key={x.id}><td>{x.title}</td><td>{x.status}</td><td>{x.completed_hours}/{x.target_hours}</td><td>{x.completion_percentage}%</td><td>{x.confidence_before != null && x.confidence_after != null ? `${x.confidence_before} → ${x.confidence_after}` : '—'}</td></tr>)}</tbody></table></section>;
const TravelTimeline = ({ rows }) => <section className="card p-5"><h2 className="text-xl font-semibold">Upcoming travel timeline</h2><p className="text-sm text-gray-500 mb-3">Travel ranges, status, checklist completion, and estimated budgets.</p>{rows.length ? rows.map((x) => <div className="border-l-4 border-sky-500 pl-4 py-2" key={x.id}><strong>{x.destination}</strong><p>{x.start_date}–{x.end_date} · {x.purpose} · {x.status}</p><p>{x.checklist_completed}/{x.checklist_total} checklist items · {x.estimated_budget} {x.currency}</p></div>) : <p>No travel plans in this period.</p>}</section>;
