import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { dashboardApi, progressApi } from '../../api';
import { Card, PageLoader } from '../../components/ui';
import { PlannedChart, TrendChart } from '../../components/admin/AnalyticsCharts';

const actions = [['Add Task','/admin/tasks/new'],['Add Goal','/admin/goals/new'],['Log New Work','/admin/activities/new'],['Add Learning Item','/admin/learning'],['Log Learning Session','/admin/learning'],['Paste Opportunity Link','/admin/capture'],['Add Opportunity','/admin/opportunities/new'],['Create Travel Plan','/admin/travel/new'],['Complete Daily Review','/admin/daily-review'],['Complete Monthly Review','/admin/progress/monthly'],['View Yearly Progress','/admin/progress/yearly']];
const List = ({ title, rows, render }) => <Card hover={false}><h2 className="text-lg font-semibold mb-3">{title}</h2>{rows?.length ? rows.map(render) : <p className="text-gray-500">Nothing to show.</p>}</Card>;

export default function DashboardPage() {
    const [summary, setSummary] = useState(null), [analytics, setAnalytics] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
    useEffect(() => { Promise.all([dashboardApi.summary(), progressApi.analytics({ period: '30d' })]).then(([a, b]) => { setSummary(a); setAnalytics(b); }).catch((e) => setError(e.displayMessage || 'Could not load dashboard.')).finally(() => setLoading(false)); }, []);
    if (loading) return <PageLoader />; if (error) return <div role="alert" className="p-4 bg-red-50 text-red-700 rounded-xl">{error}</div>;
    const cards = [['Tasks completed this week',summary.tasks_completed_this_week],['Weekly completion',`${summary.weekly_completion_percentage}%`],['Today work',`${summary.today_work_minutes} min`],['Today learning',`${summary.today_learning_minutes} min`]];
    return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Productivity dashboard</h1><p className="text-gray-500">Private overview using Asia/Dhaka boundaries.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{cards.map(([name,value]) => <Card hover={false} key={name}><p className="text-sm text-gray-500">{name}</p><p className="text-2xl font-bold">{value}</p></Card>)}</div><Card hover={false}><h2 className="text-lg font-semibold mb-3">Quick actions</h2><div className="flex flex-wrap gap-2">{actions.map(([name,path]) => <Link className="px-3 py-2 rounded-lg bg-sky-600 text-white" key={name} to={path}>{name}</Link>)}</div></Card><div className="grid lg:grid-cols-2 gap-5"><List title="Today’s important tasks" rows={summary.today_tasks} render={(x) => <Link className="block py-2 border-t" key={x.id} to={`/admin/tasks/${x.id}`}>{x.title} · {x.progress_percentage}%</Link>} /><List title="Today’s goals" rows={summary.daily_goals} render={(x) => <Link className="block py-2 border-t" key={x.id} to={`/admin/goals/${x.id}`}>{x.title} · {x.current_value}/{x.target_value}</Link>} /><List title="Overdue work" rows={summary.overdue_tasks} render={(x) => <Link className="block py-2 border-t text-red-600" key={x.id} to={`/admin/tasks/${x.id}`}>{x.title}</Link>} /><List title="Opportunities closing within 7 days" rows={summary.upcoming_opportunity_deadlines} render={(x) => <Link className="block py-2 border-t" key={x.id} to={`/admin/opportunities/${x.id}`}>{x.title} · {new Date(x.deadline).toLocaleString()}</Link>} /></div><TrendChart data={analytics.daily_trend} /><PlannedChart data={analytics.planned_vs_completed} /><div className="grid lg:grid-cols-2 gap-5"><List title="Applications requiring follow-up" rows={summary.applications_needing_follow_up} render={(x) => <Link className="block py-2 border-t" key={x.id} to={`/admin/applications/${x.id}`}>{x.opportunity__title} · {x.stage}</Link>} /><List title="Upcoming travel plans" rows={summary.upcoming_travel_plans} render={(x) => <Link className="block py-2 border-t" key={x.id} to={`/admin/travel/${x.id}`}>{x.destination} · {x.start_date}</Link>} /><List title="Recently captured links" rows={summary.recently_captured_links} render={(x) => <Link className="block py-2 border-t truncate" key={x.id} to={`/admin/capture/${x.id}`}>{x.extracted_data?.title || x.url}</Link>} /><List title="Failed notifications" rows={summary.notification_failures} render={(x) => <Link className="block py-2 border-t text-red-600" key={x.id} to="/admin/reminders">{x.reminder_type} · {x.last_error}</Link>} /></div></div>;
}
