import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { activitiesApi, goalsApi, learningApi, progressApi, reviewsApi, travelApi } from '../../api';
import { Button, Card, Input, PageLoader, Textarea } from '../../components/ui';
import { fieldClass, labelFor, pageResults } from './taskOptions';

const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Dhaka' }).format(new Date());
const ErrorBox = ({ message, retry }) => message && <div role="alert" className="p-4 rounded-xl bg-red-50 text-red-700">{message} {retry && <button className="underline" onClick={retry}>Retry</button>}</div>;
const ProgressBar = ({ value, label }) => <div><div className="h-2 rounded-full overflow-hidden bg-gray-200 dark:bg-gray-700" role="progressbar" aria-label={label} aria-valuenow={value} aria-valuemin="0" aria-valuemax="100"><div className="h-full bg-sky-500" style={{ width: `${Math.min(value, 100)}%` }} /></div><span className="text-xs text-gray-500">{value}%</span></div>;

export const GoalsPage = () => {
    const [rows, setRows] = useState([]), [error, setError] = useState(''); const [loading, setLoading] = useState(true);
    const load = useCallback(() => { setLoading(true); goalsApi.list().then((value) => setRows(pageResults(value))).catch((e) => setError(e.displayMessage || 'Could not load goals.')).finally(() => setLoading(false)); }, []);
    useEffect(() => { load(); }, [load]);
    const remove = async (row) => { if (!window.confirm(`Delete “${row.title}”?`)) return; await goalsApi.delete(row.id); toast.success('Goal deleted'); load(); };
    if (loading) return <PageLoader />;
    return <div className="space-y-6"><div className="flex justify-between gap-4"><div><h1 className="text-3xl font-bold">Goals</h1><p className="text-gray-500">Daily through yearly outcomes.</p></div><Button to="/admin/goals/new">New Goal</Button></div><ErrorBox message={error} retry={load} />{!rows.length && !error ? <Card hover={false}><p className="text-gray-500">No goals yet.</p></Card> : rows.map((row) => <Card hover={false} key={row.id}><div className="flex justify-between gap-4"><div className="flex-1"><Link to={`/admin/goals/${row.id}`} className="text-xl font-semibold text-sky-600">{row.title}</Link><p className="text-sm text-gray-500">{labelFor(row.period_type)} · {labelFor(row.category)} · {labelFor(row.status)}</p><div className="mt-3"><ProgressBar value={row.completion_percentage} label={`${row.title} progress`} /></div></div><Button size="sm" variant="danger" onClick={() => remove(row)}>Delete</Button></div></Card>)}</div>;
};

const goalEmpty = { title: '', description: '', period_type: 'daily', category: 'personal', start_date: today(), end_date: today(), target_value: 1, current_value: 0, unit: 'items', status: 'active', priority: 'medium' };
export const GoalEditorPage = () => {
    const { id } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState(goalEmpty); const [loading, setLoading] = useState(Boolean(id)); const [error, setError] = useState('');
    useEffect(() => { if (id) goalsApi.get(id).then(setForm).catch((e) => setError(e.displayMessage)).finally(() => setLoading(false)); }, [id]);
    const change = (e) => setForm({ ...form, [e.target.name]: e.target.value });
    const submit = async (e) => { e.preventDefault(); if (form.end_date < form.start_date) return setError('End date cannot precede start date.'); try { const saved = id ? await goalsApi.update(id, form) : await goalsApi.create(form); toast.success('Goal saved'); navigate(`/admin/goals/${saved.id}`); } catch (err) { setError(err.displayMessage || 'Could not save goal.'); } };
    if (loading) return <PageLoader />;
    return <div className="max-w-3xl mx-auto space-y-5"><h1 className="text-3xl font-bold">{id ? form.title : 'New Goal'}</h1><Card hover={false}><form onSubmit={submit} className="space-y-4"><ErrorBox message={error} /><Input label="Title" name="title" value={form.title} onChange={change} required /><Textarea label="Description" name="description" value={form.description} onChange={change} /><div className="grid sm:grid-cols-2 gap-3">{[['period_type',['daily','weekly','monthly','quarterly','yearly','custom']],['category',['research','university','career','programming','learning','health','travel','personal','financial','other']],['status',['planned','active','completed','paused','cancelled']],['priority',['low','medium','high','critical']]].map(([name, opts]) => <label key={name}>{labelFor(name)}<select className={fieldClass} name={name} value={form[name]} onChange={change}>{opts.map((x) => <option key={x} value={x}>{labelFor(x)}</option>)}</select></label>)}</div><div className="grid sm:grid-cols-2 gap-3"><Input label="Start date" type="date" name="start_date" value={form.start_date} onChange={change} required /><Input label="End date" type="date" name="end_date" value={form.end_date} onChange={change} required /></div><div className="grid sm:grid-cols-3 gap-3"><Input label="Target" type="number" min="0.01" step="0.01" name="target_value" value={form.target_value} onChange={change} required /><Input label="Current" type="number" min="0" step="0.01" name="current_value" value={form.current_value} onChange={change} /><Input label="Unit" name="unit" value={form.unit} onChange={change} /></div><Button type="submit">Save Goal</Button></form></Card>{id && <ProgressBar value={form.completion_percentage || 0} label="Goal completion" />}</div>;
};

export const ProgressPage = ({ period = 'monthly' }) => {
    const [summary, setSummary] = useState(null), [error, setError] = useState(''); const [loading, setLoading] = useState(true);
    const [review, setReview] = useState({ summary: '', completed_work: '', lessons_learned: '', next_priorities: '', productivity_rating: 3, learning_rating: 3 });
    useEffect(() => { setLoading(true); progressApi.summary({ period }).then(setSummary).catch((e) => setError(e.displayMessage || 'Could not load progress.')).finally(() => setLoading(false)); }, [period]);
    if (loading) return <PageLoader />;
    const saveReview = async (event) => { event.preventDefault(); try { await reviewsApi.create({ ...review, period_type: period, period_start: summary.start_date, period_end: summary.end_date, productivity_rating: Number(review.productivity_rating), learning_rating: Number(review.learning_rating) }); toast.success('Progress review saved'); } catch (requestError) { setError(requestError.displayMessage || 'Could not save review.'); } };
    return <div className="space-y-6"><div><h1 className="text-3xl font-bold">{labelFor(period)} Progress</h1><p className="text-gray-500">Chart-ready summary for {summary?.start_date} to {summary?.end_date}.</p></div><ErrorBox message={error} />{summary && <><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{Object.entries(summary.summary).map(([key, value]) => <Card hover={false} key={key}><p className="text-sm text-gray-500">{labelFor(key)}</p><p className="text-2xl font-bold">{value}</p></Card>)}</div><Card hover={false}><h2 className="text-xl font-semibold mb-3">Data readiness</h2><p className="text-gray-500">{summary.daily_series.length} daily points, {summary.goal_progress.length} goals, and {summary.learning_breakdown.length} learning groups are ready for charts.</p></Card><Card hover={false}><form onSubmit={saveReview} className="space-y-3"><h2 className="text-xl font-semibold">Write {period} review</h2><Textarea label="Summary" value={review.summary} onChange={(e) => setReview({ ...review, summary: e.target.value })} /><Textarea label="Completed work" value={review.completed_work} onChange={(e) => setReview({ ...review, completed_work: e.target.value })} /><Textarea label="Lessons learned" value={review.lessons_learned} onChange={(e) => setReview({ ...review, lessons_learned: e.target.value })} /><Textarea label="Next priorities" value={review.next_priorities} onChange={(e) => setReview({ ...review, next_priorities: e.target.value })} /><div className="grid sm:grid-cols-2 gap-3"><Input label="Productivity rating (1–5)" type="number" min="1" max="5" value={review.productivity_rating} onChange={(e) => setReview({ ...review, productivity_rating: e.target.value })} /><Input label="Learning rating (1–5)" type="number" min="1" max="5" value={review.learning_rating} onChange={(e) => setReview({ ...review, learning_rating: e.target.value })} /></div><Button type="submit">Save Review</Button></form></Card></>}</div>;
};

const activityEmpty = { activity_date: today(), title: '', description: '', category: 'other', activity_type: 'work', minutes_spent: 0, progress_value: 0, result: '', challenge: '', lesson_learned: '', next_action: '' };
export const ActivitiesPage = ({ createOnly = false }) => {
    const [rows, setRows] = useState([]), [form, setForm] = useState(activityEmpty), [loading, setLoading] = useState(!createOnly), [error, setError] = useState('');
    const load = useCallback(() => activitiesApi.list().then((x) => setRows(pageResults(x))).catch((e) => setError(e.displayMessage)).finally(() => setLoading(false)), []); useEffect(() => { if (!createOnly) load(); }, [createOnly, load]);
    const change = (e) => setForm({ ...form, [e.target.name]: e.target.value }); const submit = async (e) => { e.preventDefault(); try { await activitiesApi.create({ ...form, minutes_spent: Number(form.minutes_spent), progress_value: Number(form.progress_value) }); toast.success('Activity saved'); setForm(activityEmpty); if (!createOnly) load(); } catch (err) { setError(err.displayMessage || 'Could not save activity.'); } };
    if (loading) return <PageLoader />;
    return <div className="space-y-6"><div className="flex justify-between"><h1 className="text-3xl font-bold">{createOnly ? 'New Activity' : 'Activities'}</h1>{!createOnly && <Button to="/admin/activities/new">Add Activity</Button>}</div>{createOnly && <Card hover={false}><form onSubmit={submit} className="space-y-3"><ErrorBox message={error} /><Input label="Date" type="date" name="activity_date" value={form.activity_date} onChange={change} required /><Input label="Title" name="title" value={form.title} onChange={change} required /><Textarea label="Description" name="description" value={form.description} onChange={change} /><div className="grid sm:grid-cols-2 gap-3"><Input label="Minutes" type="number" min="0" name="minutes_spent" value={form.minutes_spent} onChange={change} /><Input label="Progress value" type="number" min="0" max="100" name="progress_value" value={form.progress_value} onChange={change} /></div><Button type="submit">Save Activity</Button></form></Card>}{!createOnly && (rows.length ? rows.map((x) => <Card hover={false} key={x.id}><h2 className="font-semibold">{x.title}</h2><p className="text-sm text-gray-500">{x.activity_date} · {x.minutes_spent} minutes · {labelFor(x.activity_type)}</p></Card>) : <Card hover={false}>No activities yet.</Card>)}</div>;
};

export const LearningPage = () => {
    const { id } = useParams(); const [rows, setRows] = useState([]), [item, setItem] = useState(null), [sessions, setSessions] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
    const [form, setForm] = useState({ title: '', topic: '', skill: '', learning_type: 'course', status: 'planned', target_hours: 1, resource_url: '' }); const [session, setSession] = useState({ session_date: today(), minutes_spent: 30, topics_covered: '', new_knowledge: '' });
    const load = useCallback(async () => { setLoading(true); try { if (id) { const [one, logs] = await Promise.all([learningApi.get(id), learningApi.sessions(id)]); setItem(one); setSessions(pageResults(logs)); } else setRows(pageResults(await learningApi.list())); } catch (e) { setError(e.displayMessage || 'Could not load learning items.'); } finally { setLoading(false); } }, [id]); useEffect(() => { load(); }, [load]);
    const create = async (e) => { e.preventDefault(); try { await learningApi.create({ ...form, target_hours: Number(form.target_hours), resource_url: form.resource_url || '' }); toast.success('Learning item added'); setForm({ ...form, title: '' }); load(); } catch (err) { setError(err.displayMessage || 'Could not save item.'); } };
    const addSession = async (e) => { e.preventDefault(); try { await learningApi.addSession(id, { ...session, minutes_spent: Number(session.minutes_spent) }); toast.success('Session logged'); load(); } catch (err) { setError(err.displayMessage || 'Could not save session.'); } };
    if (loading) return <PageLoader />;
    if (id && item) return <div className="space-y-6"><div><h1 className="text-3xl font-bold">{item.title}</h1><p className="text-gray-500">{item.skill} · {labelFor(item.status)}</p></div><ErrorBox message={error} /><Card hover={false}><ProgressBar value={item.completion_percentage} label="Learning completion" /><p className="mt-3">{item.completed_hours} of {item.target_hours} hours</p></Card><Card hover={false}><form onSubmit={addSession} className="space-y-3"><h2 className="text-xl font-semibold">Log Learning Session</h2><Input label="Date" type="date" value={session.session_date} onChange={(e) => setSession({ ...session, session_date: e.target.value })} required /><Input label="Minutes" type="number" min="1" value={session.minutes_spent} onChange={(e) => setSession({ ...session, minutes_spent: e.target.value })} required /><Textarea label="Topics covered" value={session.topics_covered} onChange={(e) => setSession({ ...session, topics_covered: e.target.value })} /><Button type="submit">Save Session</Button></form></Card>{sessions.map((x) => <Card hover={false} key={x.id}><strong>{x.session_date} · {x.minutes_spent} minutes</strong><p>{x.topics_covered}</p></Card>)}</div>;
    return <div className="space-y-6"><h1 className="text-3xl font-bold">Learning</h1><ErrorBox message={error} /><Card hover={false}><form onSubmit={create} className="grid sm:grid-cols-2 gap-3"><Input label="Title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /><Input label="Topic" value={form.topic} onChange={(e) => setForm({ ...form, topic: e.target.value })} /><Input label="Skill" value={form.skill} onChange={(e) => setForm({ ...form, skill: e.target.value })} /><Input label="Target hours" type="number" min="0" step="0.25" value={form.target_hours} onChange={(e) => setForm({ ...form, target_hours: e.target.value })} /><Button type="submit">Add Learning Item</Button></form></Card>{rows.length ? rows.map((x) => <Card hover={false} key={x.id}><Link className="font-semibold text-sky-600" to={`/admin/learning/${x.id}`}>{x.title}</Link><p className="text-sm text-gray-500">{x.skill || x.topic} · {x.completion_percentage}%</p></Card>) : <Card hover={false}>No learning items yet.</Card>}</div>;
};

const travelEmpty = { title: '', destination: '', purpose: 'personal', status: 'idea', start_date: today(), end_date: today(), estimated_budget: 0, actual_cost: 0, currency: 'BDT', transportation: '', accommodation: '', notes: '' };
export const TravelPage = ({ createOnly = false }) => {
    const { id } = useParams(); const navigate = useNavigate(); const [rows, setRows] = useState([]), [plan, setPlan] = useState(null), [form, setForm] = useState(travelEmpty), [itinerary, setItinerary] = useState([]), [checklist, setChecklist] = useState([]), [loading, setLoading] = useState(!createOnly), [error, setError] = useState('');
    const [checkTitle, setCheckTitle] = useState('');
    const load = useCallback(async () => { setLoading(true); try { if (id) { const [one, trip, checks] = await Promise.all([travelApi.get(id), travelApi.itinerary(id), travelApi.checklist(id)]); setPlan(one); setItinerary(pageResults(trip)); setChecklist(pageResults(checks)); } else setRows(pageResults(await travelApi.list())); } catch (e) { setError(e.displayMessage || 'Could not load travel plans.'); } finally { setLoading(false); } }, [id]); useEffect(() => { if (!createOnly) load(); }, [createOnly, load]);
    const change = (e) => setForm({ ...form, [e.target.name]: e.target.value }); const create = async (e) => { e.preventDefault(); if (form.end_date < form.start_date) return setError('End date cannot precede start date.'); try { const saved = await travelApi.create(form); toast.success('Travel plan saved'); navigate(`/admin/travel/${saved.id}`); } catch (err) { setError(err.displayMessage || 'Could not save travel plan.'); } };
    const addCheck = async (e) => { e.preventDefault(); await travelApi.addChecklist(id, { title: checkTitle, category: 'other' }); setCheckTitle(''); load(); };
    const remove = async () => { if (!window.confirm(`Delete “${plan.title}”?`)) return; await travelApi.delete(id); navigate('/admin/travel'); };
    if (loading) return <PageLoader />;
    if (createOnly) return <div className="max-w-3xl mx-auto space-y-5"><h1 className="text-3xl font-bold">New Travel Plan</h1><Card hover={false}><form onSubmit={create} className="space-y-3"><ErrorBox message={error} /><Input label="Title" name="title" value={form.title} onChange={change} required /><Input label="Destination" name="destination" value={form.destination} onChange={change} required /><div className="grid sm:grid-cols-2 gap-3"><Input label="Start date" type="date" name="start_date" value={form.start_date} onChange={change} required /><Input label="End date" type="date" name="end_date" value={form.end_date} onChange={change} required /><Input label="Estimated budget" type="number" min="0" name="estimated_budget" value={form.estimated_budget} onChange={change} /><Input label="Currency" name="currency" maxLength="3" value={form.currency} onChange={change} /></div><Textarea label="Transportation" name="transportation" value={form.transportation} onChange={change} /><Textarea label="Accommodation" name="accommodation" value={form.accommodation} onChange={change} /><Textarea label="Notes (do not store identification or payment credentials)" name="notes" value={form.notes} onChange={change} /><Button type="submit">Save Plan</Button></form></Card></div>;
    if (id && plan) return <div className="space-y-6"><div className="flex justify-between"><div><h1 className="text-3xl font-bold">{plan.title}</h1><p className="text-gray-500">{plan.destination} · {plan.start_date}–{plan.end_date}</p></div><Button variant="danger" onClick={remove}>Delete</Button></div><ErrorBox message={error} /><div className="grid sm:grid-cols-2 gap-4"><Card hover={false}><h2 className="font-semibold">Budget</h2><p>{plan.actual_cost} / {plan.estimated_budget} {plan.currency}</p></Card><Card hover={false}><h2 className="font-semibold">Itinerary</h2><p>{itinerary.length} scheduled items</p></Card></div><Card hover={false}><h2 className="text-xl font-semibold mb-3">Checklist</h2><form onSubmit={addCheck} className="flex gap-2"><Input label="New checklist item" value={checkTitle} onChange={(e) => setCheckTitle(e.target.value)} required /><Button type="submit">Add</Button></form>{checklist.map((x) => <p key={x.id} className="py-2 border-t border-gray-100">{x.is_completed ? '✓' : '○'} {x.title}</p>)}</Card></div>;
    return <div className="space-y-6"><div className="flex justify-between"><h1 className="text-3xl font-bold">Travel</h1><Button to="/admin/travel/new">New Plan</Button></div><ErrorBox message={error} />{rows.length ? rows.map((x) => <Card hover={false} key={x.id}><Link className="font-semibold text-sky-600" to={`/admin/travel/${x.id}`}>{x.title}</Link><p className="text-sm text-gray-500">{x.destination} · {labelFor(x.status)}</p></Card>) : <Card hover={false}>No travel plans yet.</Card>}</div>;
};
